### ISSUE TITLE
Add functionality to allow a midwife to start and end a clinic

### ISSUE THREAD

**Issue by sciritai** [TheProductWorks/smart_client#105]
## Story

As the hospital I want to be able to record when the midwives started their clinic and when they ended for reporting purposes.
## Tasks

API doc here: https://github.com/TheProductWorks/smart_client/blob/master/doc/api.md#clinic-time-records-resource
- Use the API to submit start_time and end_time for a particular date and particular clinic.
- Add some UI to allow a midwife to press a button to start and end a clinic

**Comment by Wogiebear** [comment]
What: issue scrub
When: Fri 05-06-2015
Who: Elliot, Conor

##### Feedback on the 'Check In' functionality.
- ~~Change Check In button text to "Start Clinic"~~
- ~~Change Check Out button text to "End Clinic"~~
- ~~Change 'Calendar' button on home screen to "Start/Stop Clinic"~~
- Stack the buttons
- ~~Change the title header from "SMART" to "Clinic Time"~~
- ~~Change field label "Where are you?" to "Select a clinic below"~~
- ~~Disable buttons if no clinic selected. Cater for all user error scenarios, e.g. User tries to stop a clinic that is not started.~~
- Add a 'Started' flag in green text, right-aligned to the already active clinic.

**Comment by otormaigh** [comment]
![device-2015-06-05-161505](https://cloud.githubusercontent.com/assets/10416394/8009106/388b6b4a-0b9e-11e5-9dc0-33280d6d0402.png)

Checked off some items in list.

**Comment by Wogiebear** [comment]
What: review of app
Where: BoI
Who: Elliot, Conor

## Structure of Start/Stop clinic as follows
- [x] Header text "START/STOP CLINIC"
- [x] Subsection "Clinics Started Today". It follows the subsection style.
- [x] All clinics that are already started that day appear under here as rows separated by light grey row divider. Each row has <clinic name> on left, <start time nn:mm> on right.
- [x] If not started clinic then show placeholder row containing string "No clinics currently started"... text is light grey and italicised.
- [x] Disabled CTA button [STOP CLINIC] underneath the rows. It uses 'default disabled' style
- [x] Next subsection 'Clinics Not Running'. It follows the subsection style.
- [x] All today clinics that are not started yet appear as rows under here. Each row separated by light grey row divider. Each row just lists the clinic name on the left hand side.
- [x] Disabled CTA button [START CLINIC] underneath the rows. It uses 'default disabled' style.

## User experience
1. User clicks 'Start/Stop' in home menu
2. User sees 'No clinics currently started" in Clinics Started Today subsection. User sees list of not started clinics in Clinics Not Started subsection.
3. User selects a clinic not started. 
4. Disabled [START CLINIC] becomes active
5. User clicks [START CLINIC] and sees an update progress indicator
6. User sees refreshed screen with the clinic she just started now in the 'Clinics Started Today' list.
7. User selects started clinic
8. Disabled [STOP CLINIC] becomes active
9. User clicks [STOP CLINIC] and sees an updated progress indicator
10. User sees refreshed screen with the clinic she just stopped now in the 'Clinics Not Running' subsection.

**Comment by Wogiebear** [comment]
[testing]
- delay between opening page and seeing the list of clinics 
- someway to reset the record if somebody has made a mistake

**Comment by otormaigh** [comment]
[review]
- App crashes when you touch and hold 'no clinics currently stopped' in empty Stopped queue.
- all buttons disabled by default. When user selects item in list, only then make the buttons enabled. 
- change text. 
  - "Clinics Stopped Today" -> "Already Finished Today"
  - "Clinics Started Today" -> "Already In-progress"
  - "Clinics Not Running" -> "Waiting to be Started Today"
- Rename "Reset Clinic Record" -> "Reset Clinic Times"
- change "reset" button colour to light red style

**Comment by otormaigh** [comment]
- fix app crash when click empty list
- Changed titles/button text
- disable buttons by default until user makes selection

**Comment by otormaigh** [comment]
Added Warning Call To Action style. Same as regulat CTA but button colour is now #E57373
